# Alternative: Install yara-python from pre-built wheel (Python 3.13 compatible version)
Write-Host "==================================="
Write-Host "yara-python 安装方案"
Write-Host "==================================="
Write-Host ""

$pythonExe = "C:\Python314\python.exe"
$pythonVersion = & $pythonExe --version 2>&1

Write-Host "当前 Python: $pythonVersion"
Write-Host ""
Write-Host "由于 Python 3.14 不支持 yara-python 编译，有以下选择："
Write-Host ""
Write-Host "选项 1️⃣  - 接受现状（推荐）"
Write-Host "  ✅ 应用已正常启动"
Write-Host "  ✅ 核心功能可用"
Write-Host "  ⚠️  微信 V4 自动检测不可用"
Write-Host "  ℹ️  需要时可手动提供解密密钥"
Write-Host ""
Write-Host "选项 2️⃣  - 降级到 Python 3.12"
Write-Host "  1. 从 https://www.python.org/downloads/release/python-3127/ 下载 Python 3.12"
Write-Host "  2. 安装到 C:\Python312"
Write-Host "  3. 运行: C:\Python312\python.exe -m pip install yara-python"
Write-Host "  4. 更新应用配置使用 Python 3.12"
Write-Host ""
Write-Host "选项 3️⃣  - 等待 Python 3.14 稳定"
Write-Host "  ⏳ 等待官方发布稳定版本后重新尝试"
Write-Host ""
Write-Host "==================================="
Write-Host ""
Write-Host "建议："
Write-Host "由于应用已改造为可选依赖方案，"
Write-Host "当前可以选择继续使用 Python 3.14，"
Write-Host "在需要微信 V4 功能时再升级 Python 版本。"
Write-Host ""
Write-Host "详见 web_chat/app.py 第 45-75 行"
